### ISSUE TITLE
Co potrzebne.

### ISSUE THREAD

**Issue by xav9211** [kkrzys/na-temat-crawler#1]
-Jeśli jest możliwość to funkcja która pobiera z bazy wszystkie działy
- wzorem jest funkcja List<String> getAllSectionsList()

-Następnie funkcja która przyjmując jeden z działów jako argument typu string zwraca Listę typu LinkMap (Jest to typ stworzony przeze mnie który mapuje nazwę (tytuł) z linkiem, był potrzebny bo mapy nie przechowują w kolejności dodawania. W tej zwracanej liście typu LinkMap ma  być lista miesięcy z danego działu mapowana miesiącrok z linkiem do danego miesiąca
- wzorem jest funkcja List<LinkMap> getLinksFromSection()

-Funkcja która dostając jako argument link do konkretnego miesiąca zwraca listę typu LinkMap gdzie będą przechowywane tytuły i linki artykułów z danego miesiąca.
- wzorem jest funkcja List<LinkMap> getLinksFromMonth()

-Funkcja która z bazy zwraca dane o artykule którego link bądź tytuł zostanie podany jako argument
Czyli Tytuł, autor, komentarze tekst itp.
- wzorem jest funkcja Article getArticleFromUrl()

-Funkcja która dostając zbiór od funkcji getAllArticlesLinks (zbiór linków) łączy się z każdym linkiem którego nie ma w bazie i zapisuje artykuł (dane o nim do bazy). W tej funkcji powinny być wysyłane te notyfikacje na maila co zostało wykonane itp.

**Comment by kklimexk** [comment]
Dobra ok. Sa dosyc istotne zmiany. Na poczatek przenioslem ten Controller do pakietu GUI to sobie znajdziesz. Stworzylem nowa klase do uruchamiania GUI bo byla polaczona z tym co ja zrobilem :p Nazywa sie ona: NaTematCrawlerGuiApp - to jest Twoj main jak cos ;) 

A jesli chodzi o te metody bazodanowe no to nie da sie zrobic dokladnie na wzor Twoich bo ja w bazie nie przechowuje tych ze tak powiem "posrednich" linkow. Ja tam mam artykuly, sekcje, komentarze, wiec udostepnilem Ci duzo roznych metod z tym zwiazanych. W klasie Controller podpiąłem wszystkie komponenty (bazodanowy, ten crawler service co juz byl oraz notification).

Tak więc w Controller.java jest cos takiego jak:

private NaTematCrawlerDB naTematCrawlerDB;

To jest komponent bazodanowy. On zawiera trzy serwisy czyli:

ArticleService articleService = naTematCrawlerDB.getArticleService();
CommentService commentService = naTematCrawlerDB.getCommentService();
SectionService sectionService = naTematCrawlerDB.getSectionService();

I na każdym z tych serwisów możemy wołać metody np.

articles = articleService.findArticlesBySectionName("Zdrowie"); => pobranie artykułow z sekcji "Zdrowie"

Article article = articleService.findByUrlId(String urlId); => pobranie artykułu po jego linku

comments = commentService.findCommentsForArticle(Article article) => pobranie komentarzy dla danego artykułu.

articles = articleService.findArticlesByCreatedDate("2015-05-20") => pobranie artykułow z danej daty (może być podane też tak: "2015-05" albo "2015")

articles = articleService.findArticlesBySectionNameAndCreatedDate("Zdrowie", "2015-05-20") => pobranie artykułow z danej sekcji oraz z danej daty (może być podane też tak: "2015-05" albo "2015")

sections =  sectionService.findAllSections() => metoda pobierające wszystkie sekcje

sectionService.saveSection(Section section) => metoda zapisująca sekcję do bazy

i wiele innych.
